### PR TITLE
Async validations

### LINKED ISSUE #1: Asynchronous validation
Currently the validation is only synchronous, we could add async support. With async/await this should be straightforward, but we might want to support older Swift versions too.

### PR DESCRIPTION
**Pull request by mkj-is**
Closes #1.

### CODE REVIEW

**Comment by mkj-is** [comment]
Have a look at this, @prochazkafilip. Me and @dknvmlhok are experimenting with async validation in FormStateKit. I think it might interest you since you pointed up this issue.

**Comment by prochazkafilip** [comment]
> Have a look at this, @prochazkafilip. Me and @dknvmlhok are experimenting with async validation in FormStateKit. I think it might interest you since you pointed up this issue.

Good job, it looks cool 👌. The only one think I'm thinking about is a way of async validations execution. You execute it sequentially, but I'm not sure if parallel way wouldn't be better in some cases 🤔.

**Comment by dknvmlhok** [comment]
> > Have a look at this, @prochazkafilip. Me and @dknvmlhok are experimenting with async validation in FormStateKit. I think it might interest you since you pointed up this issue.
> 
> Good job, it looks cool 👌. The only one think I'm thinking about is a way of async validations execution. You execute it sequentially, but I'm not sure if parallel way wouldn't be better in some cases 🤔.

That's why I'm gonna make an example app where we can try some of these edgecases 😉

**Comment by mkj-is** [comment]
Closing this due to inactivity.

**Pull request closed without merging**
